### ISSUE TITLE
Problem with model download

### ISSUE THREAD

**Issue by Rain-ctrl** [esa-codes/Subtitle-Creator-Burner#1]
Hello,

I would like to report an issue I encountered while using the application.

I downloaded the different models without any issues until the "large" model. The application froze and displayed a "killed" message from the terminal, then closed. The problem I’m facing now is that even though the large model download completes successfully, it still shows as "Not downloaded."

![image](https://github.com/user-attachments/assets/541b3013-c52b-45a7-bdcb-dafa78413b22)

I attempted to manually delete the model from the files, but it seems that it is not being downloaded within the cloned repository.

I am using WSL 2, Debian.

**Comment by esa-codes** [comment]
Thank you for reporting this issue. The problem has been identified and fixed.

The issue was occurring because Whisper downloads the large model as "large-v3.pt", but our application was looking for "large.pt". This mismatch caused the app to report the model as "Not downloaded" even after a successful download.

We have also corrected the displayed model sizes to be more accurate. The large model is actually 2.9GB, not 6GB as previously shown.

These fixes are now included in the latest version. The application should now correctly recognize the large model after download.

Please update to the latest version and let us know if you experience any other issues.

**Comment by Rain-ctrl** [comment]
I confirm that everything is fine now. I’m closing the issue. Thank you.
